# Generated by Django 2.1.5 on 2019-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_remove_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('STD', 'PHP'), ('MGR', 'JAVA'), ('SRMGR', 'PYTHON'), ('PRES', 'JAVASCRIPT')], max_length=25),
        ),
    ]
