# Generated by Django 2.1.5 on 2019-01-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_auto_20190111_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='skils',
        ),
    ]
