# Generated by Django 2.1.5 on 2019-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_auto_20190111_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_expierience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
