# Generated by Django 2.1.5 on 2019-02-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_auto_20190206_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='skils',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='work_expierience',
            new_name='work_experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
