# Generated by Django 2.1.5 on 2019-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_auto_20190206_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/technology/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/emp/'),
        ),
    ]
