# Generated by Django 2.1.5 on 2019-02-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_auto_20190206_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='tech_id',
        ),
    ]
