# Generated by Django 2.1.5 on 2019-02-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_auto_20190206_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=30)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Technology')),
            ],
        ),
    ]
