# Generated by Django 2.1.5 on 2019-02-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_emptech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptech',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee'),
        ),
        migrations.AlterField(
            model_name='emptech',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='tech_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
