# Generated by Django 2.1.5 on 2019-02-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0010_auto_20190208_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='technology',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emp_app.Technology'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='tech_name',
            field=models.CharField(choices=[('PHP', 'PHP'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C#', 'C#'), ('Java', 'Java'), ('C', 'C'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SQL', 'SQL'), ('TypeScript', 'TypeScript'), ('Ruby', 'Ruby')], max_length=100),
        ),
    ]
